substitutions:
  device_id: my-mr24hpc1-sensor
  device_name: My MR24HPC1 Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

api:
  encryption:
    key: "{{YOUR ENCRYPTION KEY}}"

ota:
  password: "{{YOUR OTA PASSWORD}}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  device_base: !include packages/mr24hpc1.yaml

# packages:
#   remote_package:
#     url: https://github.com/thefipster/esphome-mmwave-sensors
#     ref: release
#     files: [packages/mr24hpc1.yaml]
