substitutions:
  device_id: my-mr24hpb1-sensor
  device_name: My MR24HPB1 Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

api:
  encryption:
    key: "{{YOUR ENCRYPTION KEY}}"

ota:
  password: "{{YOUR OTA PASSWORD}}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  device_base: !include packages/mr24hpb1.yaml
