substitutions:
  device_id: test-mmwave-mr24hpc1
  device_name: Test mmWave MR24HPC1
  header_frame: header/rx_frame.h
  header_sensor: header/mr24hpc1.h
  uart_rx_pin: "16"
  uart_tx_pin: "17"

esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  includes:
  - ${header_frame}
  - ${header_sensor}

logger:
  logs:
    sensor: INFO
  
uart:
  id: uart2
  baud_rate:  115200
  rx_pin: ${uart_rx_pin}
  tx_pin: ${uart_tx_pin}

sensor:
  - platform: custom
    lambda: |-
      auto mr24hpc1 = new MR24HPC1(id(uart2)); 
      App.register_component(mr24hpc1);
      return { mr24hpc1->presence_sensor, mr24hpc1->motion_sensor, mr24hpc1->proximity_sensor, mr24hpc1->body_sensor };
    sensors:
      - id: presence_sensor
        name: MR24HPC1 Internal Presense Sensor
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: mr24hpc1_presence_template
              state: !lambda return x > 0;
      - id: motion_sensor
        name: MR24HPC1 Internal Motion Sensor
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: mr24hpc1_motion_template
              state: !lambda return x > 0;
      - id: proximity_sensor
        name: MR24HPC1 Proximity
        state_class: measurement   
      - id: body_sensor
        name: MR24HPC1 Body Movement
        state_class: measurement   

binary_sensor:
  - platform: template
    id: mr24hpc1_presence_template
    name: MR24HPC1 Presence
    device_class: occupancy
  - platform: template
    id: mr24hpc1_motion_template
    name: MR24HPC1 Motion
    device_class: motion

button:
  - platform: template
    id: mr24hpc1_reset
    name: MR24HPC1 Module Reset
    icon: mdi:power-cycle
    on_press:
      then:
        - uart.write: [ 0x53,0x59,0x01,0x02,0x00,0x01,0x0F,0xBF,0x54,0x43 ]

  - platform: template
    id: mr24hpc1_presence_inquiry
    name: MR24HPC1 Presence Inquiry
    icon: mdi:refresh
    on_press:
      then:
        - uart.write: [ 0x53,0x59,0x80,0x81,0x00,0x01,0x0F,0xBD,0x54,0x43 ]

  - platform: template
    id: mr24hpc1_motion_inquiry
    name: MR24HPC1 Motion Inquiry
    icon: mdi:refresh
    on_press:
      then:
        - uart.write: [ 0x53,0x59,0x80,0x82,0x00,0x01,0x0F,0xBE,0x54,0x43 ]

  - platform: template
    id: mr24hpc1_proximity_inquiry
    name: MR24HPC1 Proximity Inquiry
    icon: mdi:refresh
    on_press:
      then:
        - uart.write: [ 0x53,0x59,0x80,0x8B,0x00,0x01,0x0F,0xC7,0x54,0x43 ]

select:
  - platform: template
    id: mr24hpc1_scene_mode
    name: MR24HPC1 Scene Mode
    icon: mdi:home-map-marker
    optimistic: true
    options:
      - Living room
      - Bedroom
      - Bathroom
      - Area detection
    initial_option: Living room
    set_action:
      - uart.write: !lambda
                  auto index = id(mr24hpc1_scene_mode).index_of(x);
                  uint8_t value = (uint8_t)index.value() + 1;
                  uint8_t crc = value + 0xB9;
                  return { 0x53,0x59,0x05,0x07,0x00,0x01,value,crc,0x54,0x43 };  

  - platform: template
    id: mr24hpc1_unoccupied_time
    name: MR24HPC1 Time until unoccupied
    icon: mdi:timeline-clock
    optimistic: true
    options:
      - "None"
      - "10s"
      - "30s"
      - "1min"
      - "2min" 
      - "5min" 
      - "10min"
      - "30min"
      - "1hour"
    initial_option: 30s
    set_action:
      - uart.write: !lambda
                  auto index = id(mr24hpc1_unoccupied_time).index_of(x);
                  uint8_t value = (uint8_t)index.value();
                  uint8_t crc = value + 0x37;
                  return { 0x53,0x59,0x80,0x0a,0x00,0x01,value,crc,0x54,0x43 };

number:
  - platform: template
    id: mr24hpc1_sensitivity
    name: MR24HPC1 Sensitivity
    icon: mdi:tune
    min_value: 0
    max_value: 3
    optimistic: true
    step: 1
    set_action:
      - uart.write: !lambda
                    uint8_t value = (uint8_t)x;
                    uint8_t crc = x + 0xBA;
                    return { 0x53,0x59,0x05,0x08,0x00,0x01,value,crc,0x54,0x43 };